# Generated by Django 5.2.1 on 2025-07-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulatorio',
            fields=[
                ('idamb', models.AutoField(db_column='idAmb', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=45, null=True)),
                ('capacidade', models.IntegerField(blank=True, null=True)),
                ('andar', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Ambulatório',
                'verbose_name_plural': 'Ambulatórios',
                'db_table': 'ambulatorio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('idconsulta', models.AutoField(db_column='idConsulta', primary_key=True, serialize=False)),
                ('data', models.DateField(blank=True, null=True)),
                ('horario', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'db_table': 'consulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('idconv', models.AutoField(db_column='idConv', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('plano', models.CharField(max_length=45)),
                ('carencia', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Convênio',
                'verbose_name_plural': 'Convênios',
                'db_table': 'convenio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('idmed', models.AutoField(db_column='idMed', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=45, null=True)),
                ('crm', models.IntegerField(unique=True)),
                ('especialidade', models.CharField(blank=True, max_length=45, null=True)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'db_table': 'medico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idpac', models.AutoField(db_column='idPac', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=45, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('cidade', models.CharField(blank=True, max_length=45, null=True)),
                ('doenca', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'paciente',
                'managed': False,
            },
        ),
    ]
